### ISSUE TITLE
running "tauri dev" shows error

### ISSUE THREAD

**Issue by p32929** [mdtanrikulu/react-tauri#4]
I'm actually new to the Rust world and I really wanted to try this as an alternative of ElectronJS. but its showing these errors & I googled but found no solutions so far. Can you help?

![Screenshot (66)](https://user-images.githubusercontent.com/6418354/92109772-700a5e00-ee0b-11ea-9c7e-ef96482caa92.png)

**Comment by mdtanrikulu** [comment]
Hey @p32929, I think you got those errors because of version difference. I haven't update the code base for a long time, so it would be helpful to you to check what kind of new configs added to the latest tauri version. Or if you really want to run my example, you can simply install the version I used, via; 
```
npm i -g tauri@0.5.2
``` 

Then it should work.

**Comment by p32929** [comment]
Thanks. Solved
