### ISSUE TITLE
Please update this repo

### ISSUE THREAD

**Issue by nothingismagick** [mdtanrikulu/react-tauri#8]
Tauri Beta is available, and the approach in this repo is out of date. Please follow these instructions to upgrade:

https://tauri.studio/en/docs/usage/guides/migration

**Comment by mdtanrikulu** [comment]
Hello @nothingismagick , apologize for such delay. For a long time I was focusing on some other set of tasks, finally had a chance to look into it. I see amazing progress on Tauri! 
Just made a PR for updating this repo to v1, for some reason build stucks on my end as seen below, gonna take look a bit more.

<img width="547" alt="image" src="https://user-images.githubusercontent.com/2774845/125174635-101cda80-e1c7-11eb-9ead-df2d7ccd5dd4.png">

**Comment by RayKay91** [comment]
Is the PR ready? Am looking forward to using this and playing around

**Comment by mdtanrikulu** [comment]
Hi, yes PR is ready, but still for some reason build hangs on my machine. Couldn't figure out anything better yet. In any way I am merging the PR. I would be really appreciated if you could share how things went for you while building.

**Comment by mdtanrikulu** [comment]
For now keeping this issue opened for feedbacks.

**Comment by PascalFrenz** [comment]
Hey @mdtanrikulu, just took a look at the hanging build as i faced the same problem.
I think the problem is that Tauri is trying to bundle the whole project.
Changing the `distDir`-property in the  `tauri.conf.json` to `"distDir": "../build"` got it working again.
A full rebuild now takes 130s, every consecutive build takes 16s. Size of the binary is approx. 17MB.

I think a PR is not required, but if you think otherwise, let me know 👍🏻

**Comment by mdtanrikulu** [comment]
oh that's what I was missing! thank you for your input @PascalFrenz, I am just updating it correctly.
